// packages/react/src/hooks/useKeyboard.ts
import type { KeyEvent } from "@bettertui/core";
import { useEffect } from "react";
import { useEffectEvent } from "./useEvent";
import { useRuntime } from "./useRuntime";

export interface UseKeyboardOptions {
  /** Also fire the handler on key-release events (default: false). */
  release?: boolean;
}

/**
 * Subscribe to keyboard events in the current terminal.
 *
 * ```ts
 * useKeyboard((key) => {
 *   if (key.name === "q") process.exit(0);
 * });
 * ```
 */
export function useKeyboard(
  handler: (key: KeyEvent) => void,
  options: UseKeyboardOptions = {},
): void {
  const renderer = useRuntime();
  const stableHandler = useEffectEvent(handler);

  // biome-ignore lint/correctness/useExhaustiveDependencies: stableHandler has stable identity
  useEffect(() => {
    const keyInput = renderer.keyInput;
    keyInput.on("keypress", stableHandler as (e: KeyEvent) => void);
    return () => {
      keyInput.off("keypress", stableHandler as (e: KeyEvent) => void);
    };
  }, [renderer, options.release]);
}

// packages/solid/src/hooks/useKeyboard.ts
/**
 * useKeyboard — subscribe to terminal key events.
 *
 * Follows SolidJS lifecycle: registers on mount, cleans up on cleanup.
 * The handler is called for every keypress; pass `options.release = true`
 * to also receive key-release events (kitty keyboard protocol required).
 */

import type { KeyEvent } from "@bettertui/core";
import { createEffect, onCleanup } from "solid-js";
import { useRenderer } from "../context/rendererContext";

export interface UseKeyboardOptions {
  /** When true, also subscribe to key-release events. Default false. */
  release?: boolean;
}

export function useKeyboard(
  handler: (event: KeyEvent) => void,
  options: UseKeyboardOptions = {},
): void {
  const renderer = useRenderer();
  const keyInput = renderer.keyInput;

  createEffect(() => {
    keyInput.on("keypress", handler);
    if (options.release) keyInput.on("keyrelease", handler);

    onCleanup(() => {
      keyInput.off("keypress", handler);
      if (options.release) keyInput.off("keyrelease", handler);
    });
  });
}
