// packages/react/src/hooks/useTheme.ts
import { createDarkTheme, createLightTheme } from "@bettertui/core";
import type { NapiTheme } from "@bettertui/core";
import { useMemo } from "react";

export type ThemeMode = "dark" | "light";

/**
 * Returns a theme token object for the given mode (default: dark).
 * The theme is memoised and only recreated when `mode` changes.
 */
export function useTheme(mode: ThemeMode = "dark"): NapiTheme {
  return useMemo(() => (mode === "light" ? createLightTheme() : createDarkTheme()), [mode]);
}

// packages/solid/src/hooks/useTheme.ts
/**
 * useTheme — reactive NapiTheme accessor.
 *
 * Returns the dark or light theme object from the native engine.
 * The theme is memoised per `mode` using a Solid memo so repeated calls
 * within the same component share the same instance.
 */

import { createDarkTheme, createLightTheme } from "@bettertui/core";
import type { NapiTheme } from "@bettertui/core";
import { createMemo } from "solid-js";

export type ThemeMode = "dark" | "light";

export function useTheme(mode: ThemeMode = "dark"): () => NapiTheme {
  return createMemo(() => (mode === "dark" ? createDarkTheme() : createLightTheme()));
}
